#!/bin/bash
INPUT=$1     # name of input file
TIMESTEP=$2  # "default" to look at each forecast increment ; (sec) otherwise
ADVISORY=$3  # set to 025, 030, 035, Hindcast, etc
FRAME=$4     # 0 for whole fort.22; otherwise set to frame of interest
MYPROC=$5    # processor number in parallel (0 in serial)
ADCIRCDIR=$6 # directory where adcirc executables are located
ASGSDIR=$7
PERL5LIB=$8
MESHFILE=$9  # "auto" if mesh should be autogenerated
DESCRIPT=${10}
#
export PERL5LIB
ASWIPTIMESTEP=""
VORTVIZTIMESTEP=""
ASWIPFRAMEOPT=""
VORTVIZFRAMEOPT=""
MESHFILEOPT=""
#
if [ $TIMESTEP != "default" ]; then
   ASWIPTIMESTEP="-o $TIMESTEP"
   VORTVIZTIMESTEP="--outputincrement $TIMESTEP"
fi
if [ $FRAME != "0" ]; then
   ASWIPFRAMEOPT="-f $FRAME"
   VORTVIZFRAMEOPT="--frame $FRAME"
fi
if [ $MESHFILE = auto ]; then
   MESHFILEOPT="-e ${ASGSDIR}/output/spatial_5a_1r.ele"
else
   MESHFILEOPT="-i $MESHFILE"
fi
#
# write full circle Rmaxes data
$ADCIRCDIR/aswip -m 2 -w $INPUT -a $ASWIPTIMESTEP $ASWIPFRAMEOPT
# write radial v and p
$ADCIRCDIR/aswip -m 2 -w $INPUT -v $ASWIPTIMESTEP $ASWIPFRAMEOPT
# generate shell script(s) that will create maps in gmt
perl ${ASGSDIR}/output/vortex_viz_gen.pl --advisorynum $ADVISORY $VORTVIZTIMESTEP $VORTVIZFRAMEOPT
# execute shell script to create figures with gmt
chmod +x plot_radii.sh
./plot_radii.sh
# execute gnuplot script to create line graphs with gmt
gnuplot radial_v_and_p.gp
#
# create 3D viz of surface wind speeds
echo "generating spatial wind field with $ADCIRCDIR/aswip -m 2 -w $INPUT -s $ASWIPTIMESTEP $ASWIPFRAMEOPT $MESHFILEOPT"
$ADCIRCDIR/aswip -m 2 -w $INPUT -s $ASWIPTIMESTEP $ASWIPFRAMEOPT $MESHFILEOPT # write spatial v and p
files=""
if [ $FRAME = "0" ]; then
   files=`ls spatial_data_???.d`
else
   files=`printf "spatial_data_%03d.d" $FRAME`
fi
for file in $files; do
   num=`expr substr $file 14 3`
   if [ $MESHFILE = auto ]; then
      python ${ASGSDIR}/output/tristreamline.py -f $num -a "$DESCRIPT"
   else
      python ${ASGSDIR}/output/unstreamline.py $num
   fi
done
#
# make a montage of the radii, v(r) plot, p(r) plot, and 3D viz
files=""
if [ $FRAME = "0" ]; then
   files=`ls radii_???.ps`
else
   files=`printf "radii_%03d.ps" $FRAME`
fi
for file in $files; do
   num=`expr substr $file 7 3`
   convert -rotate 90 radii_${num}.ps radii_${num}.png
   convert -rotate 90 radialv_${num}.ps radialv_${num}.png
   convert -rotate 90 radialp_${num}.ps radialp_${num}.png
   montage radii_${num}.png spatial_data_${num}.png radialv_${num}.png radialp_${num}.png -geometry +2+2 montage_geom_fullsize_${num}.gif
   convert -resize 50% montage_geom_fullsize_${num}.gif montage_geom_${num}.jpg
done
