#!/bin/bash
te=2592000; ts=2502588; adv=init
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2613600; ts=2524188; adv=01
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2635200; ts=2545788; adv=02
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2656800; ts=2567388; adv=03
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2678400; ts=2588988; adv=04
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2700000; ts=2610588; adv=05
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2710800; ts=2621388; adv=06
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2721600; ts=2632188; adv=07
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2743200; ts=2653788; adv=08
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2743200; ts=2653788; adv=09
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2764800; ts=2675388; adv=10
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2786400; ts=2696988; adv=11
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2808000; ts=2718588; adv=12
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2829600; ts=2740188; adv=13
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2851200; ts=2761788; adv=14
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2872800; ts=2783388; adv=15
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2894400; ts=2804988; adv=16
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2916000; ts=2826588; adv=17
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2937600; ts=2848188; adv=18
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2959200; ts=2869788; adv=19
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=2980800; ts=2891388; adv=20
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3002400; ts=2912988; adv=21
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3024000; ts=2934588; adv=22
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3045600; ts=2956188; adv=23
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3067200; ts=2977788; adv=24
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3088800; ts=2999388; adv=25
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3110400; ts=3020988; adv=26
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3132000; ts=3042588; adv=27
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3153600; ts=3064188; adv=28
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3175200; ts=3085788; adv=29
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3196800; ts=3107388; adv=30
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3218400; ts=3128988; adv=31
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3240000; ts=3150588; adv=32
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3261600; ts=3172188; adv=33
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3283200; ts=3193788; adv=34
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3304800; ts=3215388; adv=35
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3326400; ts=3236988; adv=36
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3348000; ts=3258588; adv=37
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3369600; ts=3280188; adv=38
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3391200; ts=3301788; adv=39
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3412800; ts=3323388; adv=40
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3434400; ts=3344988; adv=41
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3456000; ts=3366588; adv=42
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3477600; ts=3388188; adv=43
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3499200; ts=3409788; adv=44
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3520800; ts=3431388; adv=45
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3542400; ts=3452988; adv=46
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
te=3564000; ts=3474588; adv=47
offsetOptions="commandLineOptions=true; refwlmode=2; writeoutfil=63; filstations='/home/ncfs/offset_source_stations.txt'; csyear=2016; csmonth=8; csday=29; cshour=12; csmin=0; cssec=0; timesecStart=$ts ; timesecEnd=$te ; filmesh='/projects/ncfs/data/asgs24614/23/nowcast/fort.14'; filrefwl='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.processedStations.dat'; filfaroff='/home/ncfs/asgs/2014stable/input/data_assimilation/FarOffV1.mat'; filinl='/home/ncfs/asgs/2014stable/input/data_assimilation/InlandV1.mat';  filout='/projects/ncfs/data/matthsofs1ft_round1/stationfiles/$adv.end.surface.63'; "
matlab -nodisplay -nosplash -nodesktop -r "${offsetOptions} try, run('/home/ncfs/asgs/2014stable/input/data_assimilation/offsetSurfaceGen.m'), catch me, fprintf('%s / %s\n',me.identifier,me.message), end, exit"
