Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.10"
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y build-essential
     apt-get install -y gfortran
     apt-get install -y --fix-missing libnetcdf-dev libnetcdff-dev
  SHELL
  config.vm.provision "file", source: "../general/init-openmpi.sh", destination: "$HOME/init-openmpi.sh"
  config.vm.provision "file", source: "../general/init-adcirc.sh", destination: "$HOME/init-adcirc.sh"
end
