# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

ENV["LC_ALL"] = "en_US.UTF-8"
Vagrant.configure("2") do |config|
  config.vm.box       = "oraclelinux/8"
  config.vm.box_url   = "https://oracle.github.io/vagrant-projects/boxes/oraclelinux/8.json"

  # as root
  config.vm.provision "shell", inline: <<-SHELL
    yum groupinstall -y 'Development Tools'
    yum install -y gcc-gfortran openssl-devel.x86_64 tmux vim
    passwd vagrant <<EOPASSWORD
asgsnosecrets!
asgsnosecrets!
EOPASSWORD
  SHELL

  # as vagrant user
  config.vm.provision "file", source: "./default.ssh-config", destination: "$HOME/.ssh/config"
  config.vm.provision "file", source: "./default.asgs-global.conf", destination: "$HOME/asgs-global.conf"
  config.vm.provision "shell", inline: <<-SHELL, privileged: false
    # fix permissions
    chmod 600 ~/asgs-global.conf
    chmod 600 ~/.ssh/config
    if [ ! -d "$HOME/asgs" ]; then
      git clone https://github.com/StormSurgeLive/asgs.git || echo git clone went wonky .. moving along
    fi
    cd "$HOME/asgs"
    ./init-asgs.sh -b -x "--run-steps openmpi"         || echo "openmpi         - something went wonky"
    ./init-asgs.sh -b -x "--run-steps hdf5"            || echo "hdf5            - something went wonky"
    ./init-asgs.sh -b -x "--run-steps netcdf4"         || echo "netcdf4         - something went wonky"
    ./init-asgs.sh -b -x "--run-steps wgrib2"          || echo "wgrib2          - something went wonky"
    ./init-asgs.sh -b -x "--run-steps cpra-postproc"   || echo "cpra-postproc   - something went wonky"
    ./init-asgs.sh -b -x "--run-steps output"          || echo "output          - something went wonky"
    ./init-asgs.sh -b -x "--run-steps util"            || echo "util            - something went wonky"
    ./init-asgs.sh -b -x "--run-steps input-mesh"      || echo "input-mesh      - something went wonky"
    ./init-asgs.sh -b -x "--run-steps input-nodalattr" || echo "input-nodalattr - something went wonky"
    ./init-asgs.sh -b -x "--run-steps perl"            || echo "perl            - something went wonky"
    ./init-asgs.sh -b -x "--run-steps perl-modules"    || echo "perl-modules    - something went wonky"
    ./init-asgs.sh -b -x "--run-steps image-magick"    || echo "image-magick    - something went wonky"
    ./init-asgs.sh -b -x "--run-steps python3"         || echo "python3         - something went wonky"
    ./init-asgs.sh -b -x "--run-steps ffmpeg"          || echo "ffmpeg          - something went wonky"
    ./init-asgs.sh -b -x "--run-steps gnuplot"         || echo "gnuplot         - something went wonky"
    ./init-asgs.sh -b -x "--run-steps units"           || echo "units           - something went wonky"
    ./init-asgs.sh -b -x "--run-steps nco"             || echo "nco             - something went wonky"
    ./init-asgs.sh -b -x "--run-steps pigz"            || echo "pigz            - something went wonky"
  SHELL

  # mount shared directories (/work and /scratch) - contents persist on host even when VM is off or gone
  config.vm.synced_folder "scratch/"      , "/scratch", create: true
  config.vm.synced_folder "work/"         , "/work",    create: true

  # disable default share (comment out to enable"
  config.vm.synced_folder ".", "/vagrant", disabled: true
end
