#! /usr/bin/env perl

=head1 NAME

version - tell which version of actoshape this is

=head1 SYNOPSIS

version [-c]

=head1 OVERVIEW

This short script simply prints out the version tag of this copy of
actoshape.  (It finds this version tag by examining the URL from which
this copy of actoshape was checked out from subversion.)

=head1 OPTIONS

=over 4

=item -c

Concise output: just print the version tag, rather than a complete
sentence.

=back

=cut

# Subversion will automatically replace the following string with the
# repository URL corresponding to this file (using keyword expansion):
my $URL = '$URL: file:///usr/local/svn-repos/actoshape/tags/actoshape-1.0.5/version $';

my $concise = ($ARGV[0] eq "-c");

if ($concise) {
	if ($URL =~ m|/trunk/|) {
		print "trunk\n";
	} elsif ( my ($version) = ($URL =~ m|/tags/([^/]+)/|) ) {
		print "$version\n";
	} else {
		print "unknown\n";
	}
} else {
	if ($URL =~ m|/trunk/|) {
		print "This is the trunk version of actoshape.\n";
	} elsif ( my ($version) = ($URL =~ m|/tags/([^/]+)/|) ) {
		print "This is version '$version' of actoshape.\n";
	} else {
		print "This is an unknown version of actoshape.\n";
	}
}


