# @jasonfleming 20190528 : This worked for me when building FigureGen on 
# stampede2 at TACC with my custom-built netcdf libraries. 
ifort FigureGen.F90 -DNETCDF -I/work/00976/jgflemin/stampede2/local/include -L/work/00976/jgflemin/stampede2/local/lib -lnetcdf -lnetcdff -o FigureGen.x
