#!/usr/bin/env bash
#--------------------------------------------------------------------------
# etc/asgs-mon-plugins/004-instance-status-progress
#--------------------------------------------------------------------------
# Copyright(C) 2024 Brett Estrade
# Copyright(C) 2024 Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#
# The ASGS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ASGS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the ASGS.  If not, see <http://www.gnu.org/licenses/>.
#--------------------------------------------------------------------------

THIS=$(basename -- $0)

source $SCRIPTDIR/etc/asgs-mon-plugins/_bash-helper-functions.sh

# standard parameters
OLDOUT=$1     # asgs-mon saves the first line of STDOUT for each check, on the next run it gets passed back
OLDEXIT=$2    # the previous exit code is also saved and passed back 
COUNT=$3      # iternation count of asgs-mon
DELAY=$4      # number of seconds asgs-mon waits before checks 
PROFILE=$5    # this is the ASGS profile name underwhich asgs-mon is running
CONFIGFILE=$6 # config file associated with the $PROFILE 
STATEFILE=$7  # path to the statefile associated with the $PROFILE
VERBOSE=$8    # value of the "-v" flag passed t asgs-mon, so the plugin can use it if needed

OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
NOTIFY=4

PROFILE=${CY}$PROFILE${R}

INSTANCEFILE=$(get_instancefile "$STATEFILE")

# current time in unix time (seconds)
NOW=$(date +%s)

# get the unixtime associated with the last modification time of $INSTANCEFILE
FILETIME=$(date --date "$(ls --full-time -l $INSTANCEFILE | awk '{ print $6 " " $7 }' | sed 's/.[0-9]*$//g')" +%s)
DIFF=$(($NOW-$FILETIME))

if [[ $DIFF -lt 60 ]]; then
  TIMEOLD="$DIFF seconds"
elif [[ $DIFF -ge 60 && $DIFF -lt 3600 ]]; then 
  TIMEOLD="$(($DIFF/60)) minutes"
elif [[ $DIFF -ge 3600 ]]; then 
  TIMEOLD="$(($DIFF/3600)) hours"
fi

if [[ $DIFF -ge 21600  ]]; then # 6 Hours sufficient?
 cat <<EOF
 (${HPCENVSHORT} ${PROFILE} - ${YW}${THIS}${R}) ${YW}${B}WARNING${R} $TIMEOLD since INSTANCEFILE updated

$INSTANCEFILE

Suggested Remedy:

Log into $HPCENV and make sure ASGS is still running ...

Information:

System : $HPCENV
ASGS   : $SCRIPTDIR
Profile: $PROFILE

Details:

EOF

  exit $WARNING;
fi

if [[ $VERBOSE == 1 ]]; then
  echo "($HPCENVSHORT $PROFILE - ${GR}$THIS${R}) INSTANCEFILE no change in $TIMEOLD" >&2
fi 

echo -n $DIFF
exit $OK
