#!/usr/bin/env bash
#--------------------------------------------------------------------------
# etc/asgs-mon-plugins/006-rundir-du
#--------------------------------------------------------------------------
# Copyright(C) 2024 Brett Estrade
# Copyright(C) 2024 Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#
# The ASGS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ASGS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the ASGS.  If not, see <http://www.gnu.org/licenses/>.
#--------------------------------------------------------------------------

# this check just reports the total amount and change from last
# check for $RUNDIR

THIS=$(basename -- $0)

source $SCRIPTDIR/etc/asgs-mon-plugins/_bash-helper-functions.sh

# standard parameters
OLDOUT=$1     # asgs-mon saves the first line of STDOUT for each check, on the next run it gets passed back
OLDEXIT=$2    # the previous exit code is also saved and passed back 
COUNT=$3      # iternation count of asgs-mon
DELAY=$4      # number of seconds asgs-mon waits before checks 
PROFILE=$5    # this is the ASGS profile name underwhich asgs-mon is running
CONFIGFILE=$6 # config file associated with the $PROFILE 
STATEFILE=$7  # path to the statefile associated with the $PROFILE
VERBOSE=$8    # value of the "-v" flag passed t asgs-mon, so the plugin can use it if needed

OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
NOTIFY=4

PROFILE=${CY}$PROFILE${R}

# example of a plugin controlled delay
if [[ $COUNT != 1 && $(($COUNT % 5)) != 0 ]]; then
  PERIOD=$(($DELAY * 5))
  echo "($HPCENVSHORT ${CY}$PROFILE${R} - ${MG}$THIS${R}) RUNDIR check ${B}${MG}skipped${R} (run every $PERIOD seconds)" >&2
  echo -n $OLDOUT # to preserve in asgs-mon's cache for next time it's actually run
  exit $OK
fi

RAWDU=$(du $RUNDIR | tail -n 1 | awk '{print $1}')
DU=$(du -h $RUNDIR | tail -n 1 | awk '{print $1}')

DUDELTA="--"
if [[ -n "$OLDOUT" ]]; then
  DUDELTA=$(($RAWDU-$OLDOUT))
fi

if [[ $VERBOSE == 1 ]]; then
  echo "($HPCENVSHORT $PROFILE - ${GR}$THIS${R}) RUNDIR is taking up $DU, delta of $DUDELTA bytes since last check" >&2
fi 

echo -n $RAWDU
exit $OK
