#!/usr/bin/env bash
#--------------------------------------------------------------------------
# etc/asgs-mon-plugins/999-warning-test
#--------------------------------------------------------------------------
# Copyright(C) 2024 Brett Estrade
# Copyright(C) 2024 Jason Fleming
#
# This file is part of the ADCIRC Surge Guidance System (ASGS).
#
# The ASGS is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# ASGS is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the ASGS.  If not, see <http://www.gnu.org/licenses/>.
#--------------------------------------------------------------------------

THIS=$(basename -- $0)

source $SCRIPTDIR/etc/asgs-mon-plugins/_bash-helper-functions.sh

# standard parameters
ASGS_PID=$1   # asgs-mon is meant to work with a running asgs_main.sh, consider this required
OLDOUT=$2     # asgs-mon saves the first line of STDOUT for each check, on the next run it gets passed back
OLDEXIT=$3    # the previous exit code is also saved and passed back 
COUNT=$4      # iternation count of asgs-mon
DELAY=$5      # number of seconds asgs-mon waits before checks 
PROFILE=$6    # this is the ASGS profile name underwhich asgs-mon is running
CONFIGFILE=$7 # config file associated with the $PROFILE 
STATEFILE=$8  # path to the statefile associated with the $PROFILE
VERBOSE=$9    # value of the "-v" flag passed t asgs-mon, so the plugin can use it if needed

OK=0
WARNING=1
CRITICAL=2
UNKNOWN=3
NOTIFY=4

PROFILE=${CY}$PROFILE${R}

TRIGGERFILE=$ASGS_TMPDIR/.warning

if [[ -e $TRIGGERFILE ]]; then
  cat <<EOF
(${HPCENVSHORT} ${PROFILE} - ${YW}${THIS}${R}) WARNING test - trigger file exists 

Suggested Remedy:

Log into $HPCENV and delete, $TRIGGERFILE

Information:

System : $HPCENV
ASGS   : $SCRIPTDIR
Profile: $PROFILE

Details:

None

EOF

  exit $WARNING;
fi

# produces no STDERR to screen or STDOUT for asgs-mon to save
exit $OK
