asgs.version : development 
asgs.git.commit : 6de08f3f9d942b95915f9614f56657684636af2c 
asgs.git.remote : origin https://github.com/StormSurgeLive/asgs 
asgs.git.branch : issue-1354 
asgs.git.tags : no-tags 
asgs.container.cmd : 
asgs.run.hostname : kitt
instancename : Shinnecock_al112017sym_kitt_jgf
operator : jason
adcirc.time.coldstartdate : 2017090712
path.results.root : null
forcing.spinup.length : 1.0
forcing.backgroundmet : off
forcing.tidefac : on
forcing.tides : on
forcing.tides.selfattractionearthloadtide : notprovided
forcing.tropicalcyclone : on
forcing.varflux : off
forcing.staticoffset : null
forcing.schedule.cycletimelimit : 99:00:00
coupling.waves : on
hpc.hpcenv : debian.local
hpc.hpcenvshort : debian
hpc.queuesys : mpiexec
hpc.joblauncher : mpiexec -n %totalcpu%
hpc.submitstring : mpiexec 
hpc.executable.qscriptgen : 
hpc.jobs.ncpucapacity : 9999
hpc.walltimeformat : hh:mm:ss
hpc.job.default.account : desktop
hpc.job.default.queuename : null
hpc.job.default.serqueue : null
adcirc.version : v56.0.4
adcirc.singularity.sif : 
adcirc.file.input.gridfile : shinnecock_inlet_coarse.grd
adcirc.file.input.unitoffsetfile : null
adcirc.gridname : Shinnecock
adcirc.file.properties.meshproperties : shinnecock_inlet_coarse.grd.properties
adcirc.file.mesh.stdmeshname : Shinnecock
adcirc.file.input.nafile : shinnecock_nodal_attributes.template
adcirc.file.template.controltemplate : shinnecock-parameters.fort.15.template
adcirc.file.elevstations : shinnecock_stations.txt
adcirc.file.velstations : shinnecock_stations.txt
adcirc.file.metstations : shinnecock_stations.txt
adcirc.hotstartformat : netcdf
adcirc.timestepsize : 6.0
adcirc.mesh.znorth : northpole
adcirc.hotstartcomp : fulldomain
file.preppedarchive : prepped_Shinnecock_Shinnecock_al112017sym_kitt_jgf_15.tar.gz
file.hindcastarchive : prepped_Shinnecock_hc_Shinnecock_al112017sym_kitt_jgf_15.tar.gz
adcirc.minmax : reset
adcirc.control.numerics.dtdp : 6.0
adcirc.control.numerics.solver_time_integration : implicit
adcirc.control.numerics.time_weighting_coefficients : ( 0.35 0.3 0.35 )
adcirc.control.physics.lateral_turbulence : eddy_viscosity
adcirc.control.physics.eddy_viscosity_coefficient : 5.0
adcirc.control.physics.bottom_friction_limit : 0.0025
adcirc.control.physics.advection : on
adcirc.control.monitoring.nfover : (  )
adcirc.control.monitoring.log_level : INFO
adcirc.control.wetdry.h0 : 0.05
adcirc.control.wetdry.velmin : 0.02
forcing.tides.file.tide_fac : tide_fac.out
adcirc.control.physics.metcontrol.draglawstring : garratt
adcirc.control.physics.metcontrol.winddraglimit : 0.0025
adcirc.control.output.metcontrol.winddraglimit : no
adcirc.control.wetdry.noffactive : on
adcirc.control.output.wetdry.outputnodecode : no
adcirc.control.output.wetdry.outputnoff : no
adcirc.control.output.inundationoutputcontrol.inundationOutput : yes
adcirc.control.output.inundationoutputcontrol.inunThresh : 0.6
ncproj : ASGS
ncinst : Seahorse Consulting
ncsour : ADCIRC
nchist : ASGS Workflow
ncref : https://doi.org/10.1061/40990(324)48
nccom : Trusted since 2006.
nchost : www.seahorsecoastal.com
ncconv : CF
nccont : jason.fleming@adcirc.live
ncdate : 2010-05-01 00:00:00 UTC
adcirc.nodal_attributes.file.template : shinnecock_nodal_attributes.template
adcirc.nodal_attributes.activate : ( sea_surface_height_above_geoid )
adcirc.nodal_attributes.mannings_n_at_sea_floor.default.values : ( 0.02 )
adcirc.nodal_attributes.subgrid_barrier.default.values : ( 99999.0 )
adcirc.nodal_attributes.average_horizontal_eddy_viscosity_in_sea_water_wrt_depth.default.values : ( 10.0 )
adcirc.nodal_attributes.surface_submergence_state.default.values : ( 1 )
adcirc.nodal_attributes.initial_river_elevation.default.values : ( 0.0 )
adcirc.nodal_attributes.advection_state.default.values : ( -100.0 )
adcirc.nodal_attributes.sea_surface_height_above_geoid.default.values : ( 0.0 )
adcirc.nodal_attributes.surface_canopy_coefficient.default.values : ( 1 )
adcirc.nodal_attributes.internal_tide_friction.default.values : ( 0.0  0.0  0.0 )
adcirc.nodal_attributes.overland_reduction_factor.default.values : ( 0.0333 )
adcirc.nodal_attributes.surface_directional_effective_roughness_length.default.values : ( 0.0  0.0  0.0 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0 )
adcirc.nodal_attributes.elemental_slope_limiter.default.values : ( 0.05 )
adcirc.nodal_attributes.primitive_weighting_in_continuity_equation.default.values : ( 0.03 )
notification.emailnotify : no
notification.executable.notify_script : null_notify.sh
notification.email.activate_list : "null"
notification.email.new_advisory_list : "null"
notification.email.post_init_list : "null"
notification.email.job_failed_list : "null"
notification.hpc.email.notifyuser : deprecated - do not use - will be removed in the future
notification.email.asgsadmin : jason.fleming@seahorsecoastal.com
notification.email.asgsadmin_id : jgf
post.intendedaudience : developers-only
post.executable.initpost : null_post.sh
post.executable.postprocess : ( null_post.sh )
post.opendap.additionalFiles : (  )
post.opendap.excludeFiles : (  )
post.opendap.tds : ( seahorse1_tds )
post.opendap.target : 
post.file.sshkey : null
post.qualitycontrol.setting : strict
archive.executable.archive : enstorm_pedir_removal.sh
forecast.scenariopackagesize : 3
path.lastsubdir : null
scenario : nowcast
forecast.ensemblesize : 3
asgs.path.lastsubdir : null
asgs.enstorm : nowcast
enstorm : nowcast
hostname : debian.local
instance : Shinnecock_al112017sym_kitt_jgf
pseudostorm : no
intendedAudience : developers-only
WindModel : none
coupling.waves.swan.reinitializeswan : no
coupling.waves.swan.swanhscompression : no
coupling.waves.swan.swanhsfull : yes
swan.swandt : 1200
swan.input.file.swaninit : swaninit.template
forcing.metclass : tropical
forcing.stormname : 11
forcing.tropicalcyclone.vortexmodel : SYMMETRIC
forcing.tropicalcyclone.stormnumber : 11
forcing.tropicalcyclone.year : 2017
forcing.tropicalcyclone.pseudostorm : no
forcing.tropicalcyclone.forecast.trigger : rssembedded
forcing.tropicalcyclone.forecast.rsssite : filesystem
forcing.tropicalcyclone.forecast.path.fdir : /home/jason/work
forcing.tropicalcyclone.best.ftpsite : filesystem
forcing.tropicalcyclone.best.path.hdir : /home/jason/work
storm : 11
stormnumber : 11
WindModel : vortex-nws308
scenario.number : -1
storm class : HU
stormname : IRMA
forcing.tropicalcyclone.stormname : IRMA
asgs : ny
track_raw_dat : notrack
track_raw_fst : notrack
track_modified : notrack
year : 2017
mesh : Shinnecock
RunType : Nowcast
ADCIRCgrid : Shinnecock
currentcycle : 12
currentdate : 170908
advisory : 38
InitialHotStartTime : 86400.000000000000
RunStartTime : 2017090812
RunEndTime : 2017090812
ColdStartTime : 2017090712
Model : PADCSWAN
adcirc.control.numerics.im : 111111
adcirc.control.numerics.a00b00c00 : ( 0.35 0.3 0.35 )
adcirc.control.physics.nolica : 1
adcirc.control.physics.nolicat : 1
adcirc.control.monitoring.nscreen : -1000
adcirc.control.monitoring.nabout : 1
adcirc.control.physics.rnday : 1.00013888888889
adcirc.control.numerics.input.ihot : 568
adcirc.control.physics.nwp : 1
adcirc.control.physics.eslm : 5.0
adcirc.control.numerics.nffr : NO LINE HERE
adcirc.control.numerics.output.nhsinc : 14402
adcirc.control.numerics.output.nhstar : 5
adcirc.control.physics.output.noute : 3
adcirc.control.physics.output.noutv : 3
adcirc.control.numerics.ititer : 1
adcirc.control.numerics.meteorology.wtiminc_line : ( 2017 09 07 12 1 0.9 1200 )
adcirc.control.physics.output.noutm : 3
adcirc.control.physics.meteorology.bladj : 0.9
Water Surface Elevation Stations File Name : fort.61.nc
Water Surface Elevation Stations Format : netcdf
adcirc.file.output.fort.61.nc.numdatasets : 0.0400000000000063
Water Surface Elevation File Name : fort.63.nc
Water Surface Elevation Format : netcdf
adcirc.file.output.fort.63.nc.numdatasets : 0.00333333333333385
Maximum Water Surface Elevation File Name : maxele.63.nc
Maximum Water Surface Elevation Format : netcdf
adcirc.file.output.maxele.63.nc.numdatasets : 1
Water Current Velocity File Name : fort.64.nc
Water Current Velocity Format : netcdf
adcirc.file.output.fort.64.nc.numdatasets : 0.00333333333333385
Maximum Current Speed File Name : maxvel.63.nc
Maximum Current Speed Format : netcdf
adcirc.file.output.maxvel.63.nc.numdatasets : 1
Barometric Pressure Stations File Name : fort.71.nc
Barometric Pressure Stations Format : netcdf
adcirc.file.output.fort.71.nc.numdatasets : 0.0400000000000063
Wind Velocity Stations File Name : fort.72.nc
Wind Velocity Stations Format : netcdf
adcirc.file.output.fort.72.nc.numdatasets : 0.0400000000000063
Barometric Pressure File Name : fort.73.nc
Barometric Pressure Format : netcdf
adcirc.file.output.fort.73.nc.numdatasets : 0.00333333333333385
Wind Velocity File Name : fort.74.nc
Wind Velocity Format : netcdf
adcirc.file.output.fort.74.nc.numdatasets : 0.00333333333333385
Maximum Wind Speed File Name : maxwvel.63.nc
Maximum Wind Speed Format : netcdf
adcirc.file.output.maxwvel.63.nc.numdatasets : 1
Minimum Barometric Pressure File Name : minpr.63.nc
Minimum Barometric Pressure Format : netcdf
adcirc.file.output.minpr.63.nc.numdatasets : 1
Maximum Wave Radiation Stress File Name : maxrs.63.nc
Maximum Wave Radiation Stress Format : netcdf
adcirc.file.output.maxrs.63.nc.numdatasets : 1
Mean Wave Direction File Name : swan_DIR.63.nc
Mean Wave Direction Format : netcdf
adcirc.file.output.swan_DIR.63.nc.numdatasets : 0.00333333333333385
Maximum Mean Wave Direction File Name : swan_DIR_max.63.nc
Maximum Mean Wave Direction Format : netcdf
adcirc.file.output.swan_DIR_max.63.nc.numdatasets : 1
Significant Wave Height File Name : swan_HS.63.nc
Significant Wave Height Format : netcdf
adcirc.file.output.swan_HS.63.nc.numdatasets : 0.00333333333333385
Maximum Significant Wave Height File Name : swan_HS_max.63.nc
Maximum Significant Wave Height Format : netcdf
adcirc.file.output.swan_HS_max.63.nc.numdatasets : 1
Mean Wave Period File Name : swan_TMM10.63.nc
Mean Wave Period Format : netcdf
adcirc.file.output.swan_TMM10.63.nc.numdatasets : 0.00333333333333385
Maximum Mean Wave Period File Name : swan_TMM10_max.63.nc
Maximum Mean Wave Period Format : netcdf
adcirc.file.output.swan_TMM10_max.63.nc.numdatasets : 1
Peak Wave Period File Name : swan_TPS.63.nc
Peak Wave Period Format : netcdf
adcirc.file.output.swan_TPS.63.nc.numdatasets : 0.00333333333333385
Maximum Peak Wave Period File Name : swan_TPS_max.63.nc
Maximum Peak Wave Period Format : netcdf
adcirc.file.output.swan_TPS_max.63.nc.numdatasets : 1
Initially Dry File Name : initiallydry.63.nc
Initially Dry Format : netcdf
adcirc.file.output.initiallydry.63.nc.numdatasets : 1
Inundation Time File Name : inundationtime.63.nc
Inundation Time Format : netcdf
adcirc.file.output.inundationtime.63.nc.numdatasets : 1
Maximum Inundation Depth File Name : maxinundepth.63.nc
Maximum Inundation Depth Format : netcdf
adcirc.file.output.maxinundepth.63.nc.numdatasets : 1
Ever Dried File Name : everdried.63.nc
Ever Dried Format : netcdf
adcirc.file.output.everdried.63.nc.numdatasets : 1
End Rising Inundation File Name : endrisinginun.63.nc
End Rising Inundation Format : netcdf
adcirc.file.output.endrisinginun.63.nc.numdatasets : 1
