Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.10"
  config.vm.provider "virtualbox" do |vb|
    vb.memory = "2048"
    vb.cpus = "2"
  end
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update
     apt-get install -y build-essential checkinstall
     apt-get install -y gfortran
     apt-get install -y python-pip
     apt-get install -y python2.7
     ln -s /usr/bin/env /bin/env > /dev/null 2>&1 || echo /usr/bin/env already links to /bin/env
  SHELL
  config.vm.provision "file", source: "../../init-asgs.sh",        destination: "$HOME/init-asgs.sh"
  config.vm.provision "file", source: "../general/README.vagrant", destination: "$HOME/README.vagrant"
  config.vm.provision "file", source: "../general/bash_login",     destination: "$HOME/.bash_login"
end
