forcing.tropicalcyclone.best.time.end : 2022092606
forcing.tropicalcyclone.best.time.start : 2022092606
forcing.tropicalcyclone.fcst.time.end : 2022100106
forcing.tropicalcyclone.fcst.time.start : 2022092609
forcing.tropicalcyclone.stormname : IAN
storm class : HU
stormname : IAN
track_raw_dat : bal092022.dat
track_raw_fst : al092022.fst
variation veer : -25.0
