forcing.tropicalcyclone.fcst.time.end : 2021083006
forcing.tropicalcyclone.fcst.time.start : 2021082709
forcing.tropicalcyclone.stormname : IDA
stormname : IDA
track_raw_dat : bal092021.dat
track_raw_fst : al092021.fst
variation branching : 13
