forcing.tropicalcyclone.fcst.time.end : 2024101006
forcing.tropicalcyclone.fcst.time.start : 2024100709
forcing.tropicalcyclone.stormname : MILTON
stormname : MILTON
track_raw_dat : bal142024.dat
track_raw_fst : al142024.fst
variation branching : 14
