forcing.tropicalcyclone.best.time.end : 2020082406
forcing.tropicalcyclone.best.time.start : 2020082400
forcing.tropicalcyclone.fcst.time.end : 2020082906
forcing.tropicalcyclone.fcst.time.start : 2020082409
forcing.tropicalcyclone.stormname : LAURA
storm class : TS
stormname : LAURA
track_raw_dat : bal132020.dat
track_raw_fst : ./single002/al132020.fst
variation veer : -100
