name: Run Selected Install Scripts

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  run-scripts:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Ubuntu packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y build-essential checkinstall
          sudo apt-get install -y libssl-dev libexpat1-dev
          sudo apt-get install -y gfortran wget curl vim screen htop tmux git bc
          sudo apt-get install -y zip flex gawk procps
          sudo apt-get install -y zlib1g-dev

      - name: Set TERM and run install script with --update-shell
        run: |
          export TERM=xterm
          ./init-asgs.sh -b -x "--update-shell"

      - name: Run ASGS build steps
        run: |
          set -e
      
          steps=(
            openmpi
            hdf5
            netcdf4
            wgrib2
            cpra-postproc
            output
            util
            util-output
            input-mesh
            input-nodalattr
            perl
            perl-modules
            gnuplot
            units
            nco
            pigz
            jq
            asgs-lint
          )
      
          for step in "${steps[@]}"; do
            echo "=============================="
            echo "Running ASGS step: $step"
            echo "=============================="
            ./init-asgs.sh -b -x "--run-steps $step"
          done
        timeout-minutes: 240


      - name: Build All Supported ADCIRCs 
        run: |
          ./asgsh.sh -A "bash ./cloud/general/t/build-all-adcirc.sh"
        timeout-minutes: 120



